version: '3.8'

services:

  # User Service
  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user_service_container
    ports:
      - "8001:80"
    environment:
      DATABASE_URL: mysql://user_service_user:user_service_password@database:3306/user_service_db
    volumes:
      - ./user-service:/app
    depends_on:
      - database

  # Posts Service
  posts-service:
    build: 
      context: ./posts-service
      dockerfile: Dockerfile
    container_name: posts_service_container
    ports:
      - "8002:80"
    environment:
      DATABASE_URL: mysql://posts_service_user:posts_service_password@database:3306/posts_service_db
    volumes:
      - ./posts-service:/app
    depends_on:
      - database

  # Likes Service
  likes-service:
    build: 
      context: ./likes-service
      dockerfile: Dockerfile
    container_name: likes_service_container
    ports:
      - "8003:80"
    environment:
      DATABASE_URL: mysql://likes_service_user:likes_service_password@database:3306/likes_service_db
    volumes: 
      - ./likes-service:/app
    depends_on:
      - database

  # Direct Communication Service
  communication-service:
    build: 
      context: ./communication-service
      dockerfile: Dockerfile
    container_name: communication_service_container
    ports:
      - "8004:80"
    environment:
      DATABASE_URL: mysql://communication_service_user:communication_service_password@database:3306/communication_service_db
    volumes:
      - ./communication-service:/app
    depends_on:
      - database

  # Email Service
  email-service:
    build: 
      context: ./email-service
      dockerfile: Dockerfile
    container_name: email_service_container
    ports:
      - "8005:80"
    environment:
      DATABASE_URL: mysql://email_service_user:email_service_password@database:3306/email_service_db
    volumes:
      - ./email-service:/app
    depends_on:
      - database

  # RabbitMQ 
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  # MailHog 
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025  # Web UI
      - 1025:1025  # SMTP server

  # Database
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: